### PR TITLE
update to latest release

### PR DESCRIPTION
**Pull request by phobson**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This release fixed in the source repo dropped python 3.4 builds in favor of python 3.7 and corrected some small issues with some `try/except` imports

...working on the uncheched TODOs

### CODE REVIEW

**Comment by phobson** [comment]
@conda-forge-admin, please rerender

**Comment by phobson** [comment]
@ocefpaf is it cool if I drop python 2.7? It's major thorn in my side with this.

**Comment by ocefpaf** [comment]
> @ocefpaf is it cool if I drop python 2.7? It's major thorn in my side with this.

Python 2.7 what? Never heard of it :wink: 

conda-forge policy is to drop anything on Python 2.7 that is too hard to maintain, even before 2020.

**Comment by phobson** [comment]
@ocefpaf it appears the py3.6 version didn't get built. That surprises me. Should it?

**Comment by ocefpaf** [comment]
> @ocefpaf it appears the py3.6 version didn't get built. That surprises me. Should it?

I think there was a bug in latest conda/conda-forge config that was causing this. (I'm away and not up-to-date with everything, let me check.)

PS: you can see from the logs that the Python 3.6 was built as 3.7
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=73502

**Pull request merged**
