### PR TITLE
mpl workaround [skip appveyor]

### PR DESCRIPTION
**Pull request by ocefpaf**
We really need to get our new Docker image up and running :weary:

### CODE REVIEW

**Comment by pelson** [comment]
> We really need to get our new Docker image up and running :weary:

Incremental change... update it here: https://github.com/pelson/Obvious-CI/blob/master/obvious-ci.docker/linux64_obvci/Dockerfile

No reason we can't update that image in the short term.

**Comment by ocefpaf** [comment]
Done in https://github.com/pelson/Obvious-CI/pull/56

(I had hopes the new Docker image would be faster. But I guess we still have some discussions ahead of us.)

**Comment by pelson** [comment]
I've triggered a build for this (https://hub.docker.com/r/pelson/obvious-ci/builds/bzfbortnbw7itsfvjavt3pw/). Hopefully that should remove the need for the unpleasant feedstock workarounds. :+1:

**Comment by pelson** [comment]
> I had hopes the new Docker image would be faster. But I guess we still have some discussions ahead of us.

Don't worry, a solution will present itself in due course. This image is tried and tested, and the only thing that is wrong with it at this moment in time is the lack of some of the PEP513 symbols.

Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
Thanks @pelson!

**Pull request merged**
